name: CD

on:
  push:
    branches: master

permissions:
  contents: write

env:
  BUILD_OUTPUT: 'build/Build/Products/Debug'

jobs:

  build:

    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: '5'

    - name: Manage Version
      run: |
        git fetch --prune --unshallow --tags
        GIT_SHA="$(git rev-parse --short HEAD)"
        eval $(grep -m 1 "MODULE_VERSION =" itlwm.xcodeproj/project.pbxproj | tr -d ';' | tr -d '\t' | tr -d " ")
        echo "SHORT_SHA=$GIT_SHA" >> $GITHUB_ENV
        echo "ITLWM_VER=$MODULE_VERSION" >> $GITHUB_ENV

    - name: Install MacKernelSDK
      run: |
        git clone --depth=1 https://github.com/acidanthera/MacKernelSDK.git

    - name: Build itlwm
      run: |
        xcodebuild -scheme itlwm -configuration Debug -derivedDataPath build GIT_COMMIT=_${SHORT_SHA} | xcpretty && exit ${PIPESTATUS[0]}

    - name: Build AirportItlwm
      run: |
        xcodebuild -scheme "AirportItlwm (all)" -configuration Debug -derivedDataPath build GIT_COMMIT=_${SHORT_SHA} | xcpretty && exit ${PIPESTATUS[0]}

    - name: Build AirportItlwm-Sequoia15
      run: |
        xcodebuild -project itlwm.xcodeproj -target "AirportItlwm-Sonoma14.4" -configuration Debug \
          SYMROOT="$(pwd)/build/Build/Products" \
          OBJROOT="$(pwd)/build/Build/Intermediates.noindex" \
          GIT_COMMIT=_${SHORT_SHA} \
          GCC_PREPROCESSOR_DEFINITIONS='$(inherited) __IO80211_TARGET=__MAC_15_0' \
          CONFIGURATION_BUILD_DIR='$(SYMROOT)/$(CONFIGURATION)/Sequoia15' \
          | xcpretty && exit ${PIPESTATUS[0]}

    - name: Pack Artifacts
      run: |
        cd $BUILD_OUTPUT
          zip -r itlwm-v${ITLWM_VER}-${SHORT_SHA}.zip itlwm.kext
          while read -r tgt ; do
            zip -r AirportItlwm-${tgt// /_}-v${ITLWM_VER}-${SHORT_SHA}.zip "$tgt"
          done < <(find . -mindepth 1 -maxdepth 1 -type d -not -path "*.kext" | cut -c 3-)
        cd -

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kexts-${{ env.SHORT_SHA }}
        path: ${{ env.BUILD_OUTPUT }}/*.zip
        retention-days: 30

    - name: Generate Release Notes
      run: |
        echo '### Recent commits' > ReleaseNotes.md
        git log -10 --format="- %h %s" | sed '/^$/d' >> ReleaseNotes.md

    - name: Publish GitHub Release
      if: contains(github.event.head_commit.message, 'Bump version') == false
      uses: ncipollo/release-action@v1
      with:
        prerelease: false
        allowUpdates: true
        removeArtifacts: true
        bodyFile: ReleaseNotes.md
        artifacts: "${{ env.BUILD_OUTPUT }}/*.zip"
        tag: "v${{ env.ITLWM_VER }}"
        token: ${{ secrets.GITHUB_TOKEN }}
